// Bundles the API server into a single file for Vercel deployment
// Vercel's Node.js builder compiles only the entry point .ts to .js
// but doesn't bundle imported .ts files, causing 504 errors at runtime.
// This script uses esbuild to bundle everything into api/index.js.

import * as esbuild from "esbuild";
import { writeFileSync } from "fs";

const entryPoint = "api/index.ts";

console.log(`[build-api] Bundling ${entryPoint}...`);

const result = await esbuild.build({
  entryPoints: [entryPoint],
  outfile: "api/index.js",
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  sourcemap: false,
  minify: false,
  // Externalize node built-ins and packages that should be resolved at runtime
  external: [
    // Node.js built-ins
    "fs", "fs/promises", "path", "crypto", "os", "url", "stream", "util",
    "http", "https", "net", "tls", "events", "buffer", "assert",
    // Packages that should be resolved at runtime on Vercel
    "@supabase/supabase-js",
    "hono",
    "hono/*",
    "@trpc/server",
    "@trpc/server/*",
    "superjson",
    "bcryptjs",
    "openai",
    "dotenv",
    "drizzle-orm",
    "drizzle-orm/*",
    "@neondatabase/serverless",
    "postgres",
    "@libsql/client",
    "better-sqlite3",
    "sql.js",
    "mysql2",
  ],
  banner: {
    js: `// Auto-generated by scripts/build-api.mjs - DO NOT EDIT`,
  },
});

if (result.errors.length > 0) {
  console.error("[build-api] Build failed:");
  for (const err of result.errors) {
    console.error(`  ${err.text} (${err.location?.file}:${err.location?.line})`);
  }
  process.exit(1);
}

console.log("[build-api] Build succeeded: api/index.js");
